services:
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
  mariadb:
    image: 'mariadb:latest'
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: admin
  netty-native:
    image: docker.io/library/netty-native:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      retries: 5
    depends_on:
      - redis
      - mariadb
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_R2DBC_URL=r2dbc:mariadb://mariadb